// Leaflet地図の管理

let map = null;
let routeLayer = null;
let poiLayer = null;
let onRouteClickCallback = null;
let onMarkerClickCallback = null;
let onMarkerHoverCallback = null; // (index, isHovering) を受け取る外部通知用
let poiMarkers = []; // POI一覧のindexと対応する{marker, poi}配列

const POI_COLOR_DEFAULT = '#3388ff';
const POI_COLOR_HIGHLIGHT = '#ef4444';
const TURN_COLOR_DEFAULT = '#f59e0b'; // 自動追加の右左折POI用（アンバー）

function makePoiIcon(color) {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 36" width="24" height="36">
    <path d="M 12 0 C 5.4 0 0 5.4 0 12 C 0 21 12 36 12 36 C 12 36 24 21 24 12 C 24 5.4 18.6 0 12 0 Z" fill="${color}" stroke="#fff" stroke-width="1.5"/>
    <circle cx="12" cy="12" r="4.5" fill="#fff"/>
  </svg>`;
  return L.divIcon({
    html: svg,
    className: 'poi-marker-icon',
    iconSize: [24, 36],
    iconAnchor: [12, 36],
    popupAnchor: [0, -32],
  });
}

// 自動追加の右左折POI用: 円形 + 方向矢印
function makeTurnIcon(direction, color) {
  const arrow = direction === 'Left'
    ? '<path d="M 17 12 L 7 12 M 11 7 L 6 12 L 11 17" stroke="#fff" stroke-width="2.5" fill="none" stroke-linecap="round" stroke-linejoin="round"/>'
    : '<path d="M 7 12 L 17 12 M 13 7 L 18 12 L 13 17" stroke="#fff" stroke-width="2.5" fill="none" stroke-linecap="round" stroke-linejoin="round"/>';
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
    <circle cx="12" cy="12" r="11" fill="${color}" stroke="#fff" stroke-width="1.5"/>
    ${arrow}
  </svg>`;
  return L.divIcon({
    html: svg,
    className: 'poi-marker-icon',
    iconSize: [24, 24],
    iconAnchor: [12, 12],
    popupAnchor: [0, -12],
  });
}

// POIの属性（autoGenerated / direction）に応じたアイコンを返す
function makeIconForPOI(poi, highlighted) {
  if (poi.autoGenerated && (poi.type === 'Left' || poi.type === 'Right')) {
    const color = highlighted ? POI_COLOR_HIGHLIGHT : TURN_COLOR_DEFAULT;
    return makeTurnIcon(poi.type, color);
  }
  const color = highlighted ? POI_COLOR_HIGHLIGHT : POI_COLOR_DEFAULT;
  return makePoiIcon(color);
}

function initMap(elementId) {
  map = L.map(elementId).setView([35.68, 139.77], 10);
  L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
  }).addTo(map);
  routeLayer = L.layerGroup().addTo(map);
  poiLayer = L.layerGroup().addTo(map);
}

function getMap() {
  return map;
}

function setRouteClickHandler(callback) {
  onRouteClickCallback = callback;
}

function setMarkerClickHandler(callback) {
  onMarkerClickCallback = callback;
}

function setMarkerHoverHandler(callback) {
  onMarkerHoverCallback = callback;
}

function clearMap() {
  if (routeLayer) routeLayer.clearLayers();
  if (poiLayer) poiLayer.clearLayers();
}

function displayRoute(trackpoints) {
  if (routeLayer) routeLayer.clearLayers();
  if (!trackpoints || trackpoints.length === 0) return;

  const latlngs = trackpoints.map(tp => [tp.latitude, tp.longitude]);
  // クリック判定用の透明な太めのライン
  const clickable = L.polyline(latlngs, { color: '#000', weight: 16, opacity: 0, interactive: true });
  // 表示用のライン
  const polyline = L.polyline(latlngs, { color: '#2563eb', weight: 3, opacity: 0.8, interactive: false });
  routeLayer.addLayer(clickable);
  routeLayer.addLayer(polyline);
  clickable.on('click', (e) => {
    if (onRouteClickCallback) {
      onRouteClickCallback(e.latlng);
    }
  });
  map.fitBounds(polyline.getBounds(), { padding: [30, 30] });
}

function displayPOIs(pois) {
  if (poiLayer) poiLayer.clearLayers();
  poiMarkers = [];
  if (!pois || pois.length === 0) return;

  for (let i = 0; i < pois.length; i++) {
    const poi = pois[i];
    const marker = L.marker([poi.latitude, poi.longitude], { icon: makeIconForPOI(poi, false) });
    marker.bindTooltip(`${i + 1}. ${poi.name || 'POI'}`, { permanent: false });
    // マーカー上にマウスが乗ったら赤くハイライト + 一覧行にも通知
    const idx = i;
    marker.on('mouseover', () => {
      highlightPOIMarker(idx);
      if (onMarkerHoverCallback) onMarkerHoverCallback(idx, true);
    });
    marker.on('mouseout', () => {
      unhighlightPOIMarker(idx);
      if (onMarkerHoverCallback) onMarkerHoverCallback(idx, false);
    });
    // クリックで編集ポップアップ
    marker.on('click', () => {
      if (onMarkerClickCallback) onMarkerClickCallback(idx);
    });
    poiLayer.addLayer(marker);
    poiMarkers.push({ marker, poi });
  }
}

function highlightPOIMarker(index) {
  const entry = poiMarkers[index];
  if (!entry) return;
  entry.marker.setIcon(makeIconForPOI(entry.poi, true));
  entry.marker.setZIndexOffset(1000);
}

function unhighlightPOIMarker(index) {
  const entry = poiMarkers[index];
  if (!entry) return;
  entry.marker.setIcon(makeIconForPOI(entry.poi, false));
  entry.marker.setZIndexOffset(0);
}
