// Leaflet地図の管理

let map = null;
let routeLayer = null;
let poiLayer = null;
let hoverHighlightLayer = null; // クロスハイライト用の単一マーカーを置くレイヤー
let hoverHighlightMarker = null;
let onRouteClickCallback = null;
let onMarkerClickCallback = null;
let onMarkerHoverCallback = null; // (index, isHovering) を受け取る外部通知用
let onRouteHoverCallback = null; // ルート上のmousemove通知 (index|null)
let poiMarkers = []; // POI一覧のindexと対応する{marker, poi}配列
let trackpointsCache = []; // ルート上hover時に最近傍を高速計算するため保持
let googleMapsControl = null; // Google Maps 検索コントロール

const POI_COLOR_DEFAULT = '#3388ff';
const POI_COLOR_HIGHLIGHT = '#ef4444';
const TURN_COLOR_DEFAULT = '#f59e0b'; // 自動追加の右左折POI用（アンバー）

function makePoiIcon(color) {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 36" width="24" height="36">
    <path d="M 12 0 C 5.4 0 0 5.4 0 12 C 0 21 12 36 12 36 C 12 36 24 21 24 12 C 24 5.4 18.6 0 12 0 Z" fill="${color}" stroke="#fff" stroke-width="1.5"/>
    <circle cx="12" cy="12" r="4.5" fill="#fff"/>
  </svg>`;
  return L.divIcon({
    html: svg,
    className: 'poi-marker-icon',
    iconSize: [24, 36],
    iconAnchor: [12, 36],
    popupAnchor: [0, -32],
  });
}

// 自動追加の右左折POI用: 円形 + 方向矢印
function makeTurnIcon(direction, color) {
  const arrow = direction === 'Left'
    ? '<path d="M 17 12 L 7 12 M 11 7 L 6 12 L 11 17" stroke="#fff" stroke-width="2.5" fill="none" stroke-linecap="round" stroke-linejoin="round"/>'
    : '<path d="M 7 12 L 17 12 M 13 7 L 18 12 L 13 17" stroke="#fff" stroke-width="2.5" fill="none" stroke-linecap="round" stroke-linejoin="round"/>';
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
    <circle cx="12" cy="12" r="11" fill="${color}" stroke="#fff" stroke-width="1.5"/>
    ${arrow}
  </svg>`;
  return L.divIcon({
    html: svg,
    className: 'poi-marker-icon',
    iconSize: [24, 24],
    iconAnchor: [12, 12],
    popupAnchor: [0, -12],
  });
}

// POIの属性（autoGenerated / direction）に応じたアイコンを返す
function makeIconForPOI(poi, highlighted) {
  if (poi.autoGenerated && (poi.type === 'Left' || poi.type === 'Right')) {
    const color = highlighted ? POI_COLOR_HIGHLIGHT : TURN_COLOR_DEFAULT;
    return makeTurnIcon(poi.type, color);
  }
  const color = highlighted ? POI_COLOR_HIGHLIGHT : POI_COLOR_DEFAULT;
  return makePoiIcon(color);
}

function initMap(elementId) {
  map = L.map(elementId, { maxZoom: 20 }).setView([35.68, 139.77], 10);

  // 利用可能なベースタイルレイヤー
  const baseLayers = {
    'OpenStreetMap': L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
      attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
      maxZoom: 20,
      maxNativeZoom: 19,
    }),
    'CyclOSM': L.tileLayer('https://{s}.tile-cyclosm.openstreetmap.fr/cyclosm/{z}/{x}/{y}.png', {
      attribution: '<a href="https://www.cyclosm.org">CyclOSM</a> | &copy; <a href="https://www.openstreetmap.org/copyright">OSM</a>',
      maxZoom: 20,
      maxNativeZoom: 20,
    }),
    '地理院地図 / GSI': L.tileLayer('https://cyberjapandata.gsi.go.jp/xyz/std/{z}/{x}/{y}.png', {
      attribution: '<a href="https://maps.gsi.go.jp/development/ichiran.html">国土地理院</a>',
      maxZoom: 20,
      maxNativeZoom: 18,
    }),
  };

  // 保存されたレイヤーを復元、なければOSMデフォルト
  let savedName = 'OpenStreetMap';
  try {
    const saved = localStorage.getItem('routetools-tile-layer');
    if (saved && baseLayers[saved]) savedName = saved;
  } catch (e) { /* localStorage不可 */ }
  baseLayers[savedName].addTo(map);

  // レイヤー切り替えコントロール
  L.control.layers(baseLayers, null, { position: 'bottomright', collapsed: true }).addTo(map);

  // 選択をlocalStorageに保存
  map.on('baselayerchange', (e) => {
    try { localStorage.setItem('routetools-tile-layer', e.name); } catch (err) { /* ignore */ }
  });

  // Google Maps 検索コントロール（初期は非表示）
  const GoogleMapsControl = L.Control.extend({
    options: { position: 'topright' },
    onAdd: function () {
      const container = L.DomUtil.create('div', 'leaflet-bar leaflet-google-maps-control');
      const link = L.DomUtil.create('a', '', container);
      link.href = '#';
      link.title = t('button.google_maps_search');
      link.textContent = '🔍';
      link.setAttribute('role', 'button');
      link.setAttribute('aria-label', t('button.google_maps_search'));
      L.DomEvent.disableClickPropagation(container);
      L.DomEvent.on(link, 'click', function (e) {
        L.DomEvent.preventDefault(e);
        const center = map.getCenter();
        const zoom = map.getZoom();
        const query = (typeof t === 'function') ? t('google_maps.query') : 'cafe';
        const url = `https://www.google.com/maps/search/${encodeURIComponent(query)}/@${center.lat},${center.lng},${zoom}z`;
        window.open(url, '_blank', 'noopener');
      });
      return container;
    },
  });
  googleMapsControl = new GoogleMapsControl();

  routeLayer = L.layerGroup().addTo(map);
  poiLayer = L.layerGroup().addTo(map);
  hoverHighlightLayer = L.layerGroup().addTo(map);

  // レイアウト確定後にサイズを再計算（標高プロファイル分のスペースを反映してタイルを読み込み直す）
  requestAnimationFrame(() => {
    if (map) map.invalidateSize();
  });
}

function getMap() {
  return map;
}

function setRouteClickHandler(callback) {
  onRouteClickCallback = callback;
}

function setMarkerClickHandler(callback) {
  onMarkerClickCallback = callback;
}

function setMarkerHoverHandler(callback) {
  onMarkerHoverCallback = callback;
}

function setRouteHoverHandler(callback) {
  onRouteHoverCallback = callback;
}

function clearMap() {
  if (routeLayer) routeLayer.clearLayers();
  if (poiLayer) poiLayer.clearLayers();
}

function displayRoute(trackpoints) {
  if (routeLayer) routeLayer.clearLayers();
  clearRouteHighlight();
  trackpointsCache = trackpoints || [];
  if (!trackpoints || trackpoints.length === 0) return;

  const latlngs = trackpoints.map(tp => [tp.latitude, tp.longitude]);
  // クリック判定用の透明な太めのライン
  const clickable = L.polyline(latlngs, { color: '#000', weight: 16, opacity: 0, interactive: true });
  // 表示用のライン
  const polyline = L.polyline(latlngs, { color: '#2563eb', weight: 3, opacity: 0.8, interactive: false });
  routeLayer.addLayer(clickable);
  routeLayer.addLayer(polyline);
  clickable.on('click', (e) => {
    if (onRouteClickCallback) {
      onRouteClickCallback(e.latlng);
    }
  });
  clickable.on('mousemove', (e) => {
    if (!onRouteHoverCallback) return;
    const idx = findNearestTrackpointIndex(e.latlng);
    if (idx !== -1) onRouteHoverCallback(idx);
  });
  clickable.on('mouseout', () => {
    if (onRouteHoverCallback) onRouteHoverCallback(null);
  });
  map.fitBounds(polyline.getBounds(), { padding: [30, 30] });
}

// 緯度経度に最も近いトラックポイントのindexを返す（二乗距離で十分）
function findNearestTrackpointIndex(latlng) {
  if (!trackpointsCache || trackpointsCache.length === 0) return -1;
  let minD = Infinity;
  let minI = 0;
  for (let i = 0; i < trackpointsCache.length; i++) {
    const tp = trackpointsCache[i];
    const dy = tp.latitude - latlng.lat;
    const dx = tp.longitude - latlng.lng;
    const d = dx * dx + dy * dy;
    if (d < minD) { minD = d; minI = i; }
  }
  return minI;
}

// 指定座標にクロスハイライト用のマーカーを表示（既存は移動）
function setRouteHighlight(latlng) {
  if (!map || !hoverHighlightLayer) return;
  if (!hoverHighlightMarker) {
    hoverHighlightMarker = L.circleMarker(latlng, {
      radius: 6,
      color: '#ef4444',
      weight: 2,
      fillColor: '#ef4444',
      fillOpacity: 0.7,
      interactive: false,
    });
    hoverHighlightLayer.addLayer(hoverHighlightMarker);
  } else {
    hoverHighlightMarker.setLatLng(latlng);
  }
}

function clearRouteHighlight() {
  if (hoverHighlightMarker && hoverHighlightLayer) {
    hoverHighlightLayer.removeLayer(hoverHighlightMarker);
    hoverHighlightMarker = null;
  }
}

function displayPOIs(pois) {
  if (poiLayer) poiLayer.clearLayers();
  poiMarkers = [];
  if (!pois || pois.length === 0) return;

  for (let i = 0; i < pois.length; i++) {
    const poi = pois[i];
    const marker = L.marker([poi.latitude, poi.longitude], { icon: makeIconForPOI(poi, false) });
    marker.bindTooltip(`${i + 1}. ${poi.name || 'POI'}`, { permanent: false });
    // マーカー上にマウスが乗ったら赤くハイライト + 一覧行にも通知
    const idx = i;
    marker.on('mouseover', () => {
      highlightPOIMarker(idx);
      if (onMarkerHoverCallback) onMarkerHoverCallback(idx, true);
    });
    marker.on('mouseout', () => {
      unhighlightPOIMarker(idx);
      if (onMarkerHoverCallback) onMarkerHoverCallback(idx, false);
    });
    // クリックで編集ポップアップ
    marker.on('click', () => {
      if (onMarkerClickCallback) onMarkerClickCallback(idx);
    });
    poiLayer.addLayer(marker);
    poiMarkers.push({ marker, poi });
  }
}

function highlightPOIMarker(index) {
  const entry = poiMarkers[index];
  if (!entry) return;
  entry.marker.setIcon(makeIconForPOI(entry.poi, true));
  entry.marker.setZIndexOffset(1000);
}

function unhighlightPOIMarker(index) {
  const entry = poiMarkers[index];
  if (!entry) return;
  entry.marker.setIcon(makeIconForPOI(entry.poi, false));
  entry.marker.setZIndexOffset(0);
}

let googleMapsControlAdded = false;

function setGoogleMapsControlVisible(visible) {
  if (!map || !googleMapsControl) return;
  if (visible && !googleMapsControlAdded) {
    googleMapsControl.addTo(map);
    googleMapsControlAdded = true;
  } else if (!visible && googleMapsControlAdded) {
    map.removeControl(googleMapsControl);
    googleMapsControlAdded = false;
  }
}
